-- Add migration script here
DROP TABLE IF EXISTS "otp";
DROP TABLE IF EXISTS "audit_log";
DROP TYPE IF EXISTS "action";
DROP TYPE IF EXISTS "resource_type";
DROP TABLE IF EXISTS "session";
DROP TABLE IF EXISTS "user_credential";
DROP TABLE IF EXISTS "user_identity";
DROP INDEX IF EXISTS idx_user_email;
DROP INDEX IF EXISTS idx_user_phone_number;
DROP TABLE IF EXISTS "user";
