[server]
address = "127.0.0.1"
port = 3001

[database]
url = "postgres://postgres:password@localhost:5432/storage_test"

[auth]
audience = "hops-test"
issuer = "hops-test"

[otp]
ttl_minutes = 5
max_attempts = 3
max_messages_per_day = 10

[crypto]
secret = "test-secret"

[comms]
username = "test-username"
password = "test-password"
from = "Hops"
otp_message_template = "Your verification code is {code}"
